// Code generated by "genfeature"; DO NOT EDIT.

package paging

import (
	"kamrankamilli/xmpp/disco/info"
)

// A list of service discovery features that are supported by this package.
var (
	Feature = info.Feature{Var: NS}
)
