// Code generated by "genfeature -vars Feature:NS,FeatureNotify:NSNotify"; DO NOT EDIT.

package bookmarks

import (
	"github.com/kamrankamilli/xmpp/disco/info"
)

// A list of service discovery features that are supported by this package.
var (
	Feature       = info.Feature{Var: NS}
	FeatureNotify = info.Feature{Var: NSNotify}
)
