// Code generated by "genfeature -vars=Feature:NS,FeatureIQ:NS"; DO NOT EDIT.

package oob

import (
	"github.com/kamrankamilli/xmpp/disco/info"
)

// A list of service discovery features that are supported by this package.
var (
	Feature   = info.Feature{Var: NS}
	FeatureIQ = info.Feature{Var: NS}
)
