# TODO: re-enable sendxmpp, mcabber, etc.
# See: https://mellium.im/issue/68, https://mellium.im/issue/222, and
#      https://mellium.im/issue/329

steps:
  info: &info
    image: alpine:edge
    environment:
      CGO_ENABLED: "0"
      MELLIUM_INTEGRATION_SKIP: "ejabberdctl,sendxmpp,mcabber,jackal"
    commands:
      - apk update
      - apk add go python3 lua5.2
      - go version
      - go env
      - python --version
      - lua5.2 -v
  test:
    << : *info
    commands:
      - |
        cat >> /etc/apk/repositories << EOF; $$(echo)
        http://dl-cdn.alpinelinux.org/alpine/edge/testing

        EOF
      - apk update
      - apk add go python3 lua5.2 py3-slixmpp py3-aioxmpp openssl prosody lua-unbound jackal
      - go test -v -tags "integration" -run Integration ./...
depends_on:
  - dco
  - test
