steps:
  info: &info
    image: golang:1.22-alpine
    environment:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
    when:
      - event: [tag, push, pull_request, release, manual]
  test:
    << : *info
    commands: go test -v -cover ./...
  examples:
    << : *info
    directory: examples/
    commands: |
      for d in ./*/; do
        cd $d
        go build
        cd ..
      done

depends_on:
  - dco
