steps:
  info: &info
    image: golang:${GO_VERSION}-alpine
    environment:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
    when:
      - event: [tag, push, pull_request, release, manual]
  test:
    << : *info
    commands: go test -v -cover ./...
  examples:
    << : *info
    directory: examples/
    commands: |
      for d in ./*/; do
        cd $d
        go build
        cd ..
      done

matrix:
  GO_VERSION:
    - 1.23
    - 1.22

depends_on:
  - dco
